Add static components
martin-rifon/workshop-react pull request #1
Opened 2016-11-29 16:37 UTC by martin-rifon

@diegomura

Hola Diego, como andas? Che, te jodo si te pido que viches esto? Hice los componentes estaticos para el workshop.

Muchas gracias!

2016-11-29 16:48 UTC, diegomura commented
Obvio! No hay problema 😄

2016-11-29 17:23 UTC, diegomura requested changes
Tremendo trabajo!
Esta muy prolijo el código.

Solo un comentario respecto a como estas agrupando los componentes. No existe una regla de como hacerlo, sino varias escuelas. Una es hacer como vos hiciste de agrupar Componentes segun la pagina a la que pertenecen. Esto tiene como ventaja que los tenes separados con un criterio coherente, pero al querer reutilizar un componente en varias vistas, los imports te pueden quedar muy entreverados. Una opción aca es crear un directorio padre y poner los Componentes compartidos dentro, pero ahi perdes justasamente el criterio de orden.

Otra escuela es crear una carpeta Components padre, y tirar todo ahi y que cada page tome lo que necesite. Esto trae otras ventajas y desventajas.

Esta muy bien así, pero esta bueno saber otras opciones y preguntarse cual sirve mas en cada proyecto.

2016-11-29 17:23 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +  }
Constructor innecesario

2016-11-29 17:23 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryList/TimeEntryList.js
> +      super();
El constructor recibe las `props` por parámetro y se las pasa al constructor del padre (`super`)

Deberia ser: 
```
constructor(props) {
  super(props);
  //...
}

2016-11-29 17:23 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryList/TimeEntryList.js
> +                            this.state.time_entries.map(
Esto podría definirse antes del return como una `const timeEntries` y dentro del return solo hacer `{timeEntries}`.

No existe una solución correcta igual, pero aliviana bastante el return del metodo `render`.

Asimismo, se podría crear un metodo `renderTimeEntry` que es el que se pasa por parámetro al `map`

Quedaría:
```
renderTimeEntry(timeEntry) {
  return (
    <tr> /* */ </tr>
  );
}

render () {
  const {time_entries} = this.state;
  const timeEntries = time_entries.map(this.renderTimeEntry);

  return (
    //...
    <tbody>{timeEntries}</tbody>
    //...
  );
}
```

2016-11-29 17:23 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryList/TimeEntryList.js
> +          time_entries: [
Porque snake_case en este caso?
Podria estar bien pensando que asi va a ser la respuesta de la API, pero no me quedo claro si es por eso

2016-11-29 17:23 UTC, diegomura commented on src/pages/Login/Login.js
> +};
En estos casos tan simples, yo prefiero usar un `Stateless Component`. Es basicamente lo mismo, pero es una función en vez de una clase:

```
export default Login = () => (
  <div className="login">
    <h1 className="login-header">Welcome!</h1>
    <LoginForm />
  </div>
);
```

2016-11-29 17:23 UTC, diegomura commented on src/pages/Projects/Components/ProjectEntry/ProjectEntry.js
> +  render () {
Se acostumbra a hacer destructing de las props/state antes del render

`const {entry} = this.props;`

Esto evita tener que repetir una y otra vez `this.props` en el render, que deja mas comprensible el codigo JSX

2016-11-29 17:23 UTC, diegomura commented on src/pages/Projects/Components/ProjectList/ProjectList.js
> +  constructor() {
Faltan props en el constructor

2016-11-29 17:23 UTC, diegomura commented on src/pages/Projects/Components/ProjectList/ProjectList.js
> +                            )
Misma observación que antes

2016-11-29 17:23 UTC, diegomura commented on src/pages/Projects/Projects.js
> +
Otro candidato a ser `stateless component`

2016-11-29 17:30 UTC, martin-rifon commented
Buenisimo Diego, muchas gracias. Hoy de noche miro los comentarios y hago los cambios.

2016-11-30 02:32 UTC, martin-rifon commented
Diego, buenísimos los comentarios. Ya implemente todos, creo.

Respecto a lo primero, sobre como estructurar componentes. Vengo de Angular 1.x y sabia de ahí que es buena practica dividir por pagina o por feature las cosas, porque a medida que una app crecía, las carpetas como `models`, `controllers` o `components` se hacen muy grandes y encontrar algo en ellas se vuelve cada mas lento. Mas alla de esto, puedo ver como tener todos los componentes en una carpeta como `components` puede hacer las cosas mas rápido, sobre todo si la app es chica.

2016-11-30 03:07 UTC, diegomura approved these changes

2016-11-30 03:08 UTC, diegomura commented
Esta perfecto!
Entiendo lo que decís. Como dije, no hay recetas, y esta bueno experimentar opciones para ver ventajas/desventajas y con cual te sentís mas cómodo trabajando.

2016-12-01 22:45 UTC, merged