Partial progress on redux-handling
martin-rifon/workshop-react pull request #2
Opened 2016-12-02 02:16 UTC by martin-rifon

@diegomura 

Hola Diego, como va?

Te dejo algo que estuve viendo. Todavía le falta, pero era mas que nada para saber si voy por el buen camino o si hay algún error conceptual o algo que mejor resuelvo ahora.

Muchas gracias!

2016-12-02 22:05 UTC, diegomura requested changes

2016-12-02 22:05 UTC, diegomura commented on src/models/Project.js
> +class Project {
Este modelo es realmente necesario?
Porque no utilizar el objeto js mismo que devuelve la API?

2016-12-02 22:05 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +      end
porque necesitamos el `end` en el `state`?

2016-12-02 22:05 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +    const end = moment(this.state.start).add(this.state.seconds, 's');
`end` va a corresponder con el tiempo actual, por lo que no es necesario tener que calcularlo en base al `start` y a los segundos que transcurrieron.

2016-12-02 22:05 UTC, diegomura commented on src/pages/Dashboard/Containers/TimeEntryFormContainer.js
> +export default TimeEntryFormContainer
Suele utilizarse este patrón de tener Containers de Components en casos en los que a un mismo Component se va a reutilizar, inyectandole diferentes partes del estado. Es este el caso?

Normalmente, yo prefiero tener el exportar el `connect` en el Componente en si al menos que se cumpla lo de arriba. Es mas facil par luego saber que tenes que importar donde lo vayas a usar

2016-12-02 22:05 UTC, diegomura commented on src/reducers/index.js
> +
Muchos espacios en blanco

2016-12-02 22:05 UTC, diegomura commented on src/reducers/index.js
> +      newState.timeEntries.push({
No creo que esta sea una buena forma de garantizar la inmutabilidad del estado.

No se que tan costoso es el deep clone que se hace, pero sería mejor simplemente hacer `newState.timeEntries.concat({/*  data */}`

Immutable.js es una buena herramienta y se utiliza, pero no se si amerita en este caso

2016-12-02 22:05 UTC, diegomura commented on src/reducers/index.js
> +export default (state = initialState, action) => {
Para los reducers, te sugiero utilizar un patrón como el siguiente:

```
const ACTION_HANDLERS = {
  'CREATE_TIME_ENTRY': (state, action) => {
    // return new state
  },
  // ...
}

export const reducer = (state = initialState, action) => {
  const handler = ACTION_HANDLERS[action.type];

  return handler ? handler(state, action) : state;
};
```

De esta forma te garantizas que el reducer siempre devuelva un estado de una forma mas facil, y prevenís tener un método gigante. Separas las implementacione del reducer en varios reducers

2016-12-02 22:05 UTC, diegomura commented on src/app.js
> +store.subscribe(render);
Utilizando `Provider` no creo que esto sea necesario. Podes simplemente ejecutar `ReactDOM.render(<App />, document.getElementById('app'))` fuera del metodo render (chequear que lo que digo es cierto, estoy un 80% seguro 😝 )

2016-12-02 22:05 UTC, diegomura commented on src/app.js
> +const store = createStore(foogl);
`createStore` debería recibir por segundo parámetro el estado inicial

2016-12-03 13:41 UTC, martin-rifon commented on src/models/Project.js
> +class Project {
Se me ocurrió crearlo como para adelantar nomas. Supuse que eventualmente cuando se pegue contra la API, se iba a precisar un modelo que represente un proyecto. Decís que el modelo en si no es necesario en absoluto? O que no es necesario ahora mismo?

2016-12-03 13:42 UTC, martin-rifon commented on src/pages/Dashboard/Containers/TimeEntryFormContainer.js
> +export default TimeEntryFormContainer
Si, esa era la idea. Me base en http://redux.js.org/docs/basics/UsageWithReact.html, en la parte que habla de Presentational Components y de Container Components. Basicamente, entendí que para interactuar con Redux, el componente tiene que ser un Container Component y que los Container Components no tienen layout, por lo cual, separe en dos componentes.

2016-12-03 13:43 UTC, martin-rifon commented on src/reducers/index.js
> +      newState.timeEntries.push({
No me queda muy claro esto. Si mal no entendí, la idea es que el reducer sea puro, no? Por lo cual, siempre deberías obtener una deep copy del estado actual, operar sobre la copia y devolver la copia, no? Si no haces una copia, estas modificando el estado que vino por parámetro, lo cual hace la función impura, no?

2016-12-03 13:44 UTC, martin-rifon commented
Diego, subí algunos fixes y te deje algunas preguntas.

2016-12-03 16:23 UTC, diegomura commented on src/models/Project.js
> +class Project {
Yo creo que no es necesario. Generalmente no se trabaja con React de esta forma (lo cual no significa que no se pueda y no puede llegar a ser buena idea en algun caso), pero el proyecto no va a tener ninguna lógica muy compleja ni ahora ni despues. Mas que nada, lo que vas a tener que hacer es crear, eliminar y modificar proyectos en tu estado, y nada mas. Ademas, utilizando modelos es mas complicado garantizar la inmutabilidad del estado: los getters y setters que podrás tener usualmente modifican el modelo mismo. No devuelven otro.

Que posible uso le darias al modelo? Quizas se me esta pasando algo por alto

2016-12-03 16:31 UTC, diegomura commented on src/pages/Dashboard/Containers/TimeEntryFormContainer.js
> +export default TimeEntryFormContainer
Si, eso es correcto. Tambien se les llaman Dumb (solo componentes con layout) y Smart Components.

Lo que yo decia sin embargo, es que no es siempre necesario separarlos en 2 archivos diferentes cuando no tenes mas de un Container por Presentational Component (como en este caso. 

Dentro de tu app, el TimeEntryForm va a recibir siempre las mismas actions y las mismas partes del estado (es decir, no vas a tener otro Container para TimeEntryForm). Es por eso que te recomendaba exportar el `connect` directamente en TimeEntryForm y así evitarte el boilerplate de tener mas archivos y directorios innecesarios.

Aun así, si preferis ajustarte de forma mas estricta a separar los Presentational y Container Components, esta bien.

2016-12-03 20:38 UTC, martin-rifon commented on src/models/Project.js
> +class Project {
OK, veo que en realidad no es tan necesario. Lo saque. Por lo menos repase las ventajas y no habia nada que me convenciera mucho.

2016-12-03 20:39 UTC, martin-rifon commented on src/pages/Dashboard/Containers/TimeEntryFormContainer.js
> +export default TimeEntryFormContainer
Si, entiendo que las ventajas no son muy grandes en un proyecto como este y ta, lo mas importante creo es que me quedo clara la utilidad de esto. Asi que saque el container al final, pero lo tengo presente para el futuro.

2016-12-03 20:40 UTC, martin-rifon commented
Fueron los cambios que faltaban.

2016-12-03 22:09 UTC, diegomura requested changes

2016-12-03 22:09 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +      end
`end` no es mas parte del estado

2016-12-03 22:09 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +      projectName: ReactDOM.findDOMNode(this.refs.projectName).value,
usar `ref` (https://facebook.github.io/react/docs/refs-and-the-dom.html)

2016-12-03 22:09 UTC, diegomura commented on src/reducers/index.js
> +  let newState = Immutable.fromJS(state).toJS();
Sigo creyendo que esto esta demasiado complicado para algo que se soluciona con un `concat`.

El porqué esta en el hilo del commit anterior

2016-12-03 22:09 UTC, diegomura commented on src/reducers/index.js
> +      newState.timeEntries.push({
Es correcto que el reducer tiene que ser puro, pero para garantizar esto no es necesario hacer un deep copy del estado y operar sobre ella. De forma rápida, para que sea puro los requerimientos son:

- El output de la función solo debe depender del input
- No modificar los objetos que se pasan por parámetro

Si bien tu solución devuelve un objeto nuevo, lo cual esta bien, hay formas mas simples de cumplir con estas reglas.

Pongamos que `a` es el estado que se pasa por parámetro al reducer (nuestro estado original). Si nosotros hacemos simplemente un push al estado y lo retornamos (`b`), el estado esta actualizado pero si vemos el estado original tambien cambió. La función no es pura.
<img width="557" alt="screen shot 2016-12-03 at 6 51 21 pm" src="https://cloud.githubusercontent.com/assets/5600341/20862461/06eec118-b98a-11e6-9c48-2efce1d134df.png">

Sin embargo, si usamos operaciones inmutables de los objetos, como `concat`, retornamos un estado actualizado pero sin cambiar el estado original. Esto se observa en la siguiente imagen:
<img width="558" alt="screen shot 2016-12-03 at 6 51 50 pm" src="https://cloud.githubusercontent.com/assets/5600341/20862472/51ebd458-b98a-11e6-9bf7-b9330ea97c6f.png">

Se que no es lo que hiciste vos, pero los ejemplos son mas que nada para ver que no es necesario copiar todo el objeto y mutar ese para garantizar la pureza del reducer. Los objetos en JS se almacenan por referencia. No hay nada de malo en devolver un objeto con punteros a otros objetos JS que pertenecían a un estado anterior, siempre y cuando no sobrescribas los cambios a las partes que si cambiaron. Hacer un deep copy es poco optimo ya que generas nuevas instancias de la información que no cambió.

Espero esto haya aclarado las dudas 😄

2016-12-03 22:09 UTC, diegomura commented on src/reducers/index.js
> +      }
Respecto a esto, me parece que no es responsabilidad de esta action crear un proyecto. Yo comenzaría mas por un approach donde la acción se dispara con el id de un proyecto ya existente, o null si no tiene proyecto. Mas adelante vas a tener una acción de crear un proyecto, y vas a poder sino hacer el dispatch de esa acción aca si tenes interes de que el proyecto se cree al crear el time entry

2016-12-03 22:14 UTC, diegomura requested changes

2016-12-03 22:14 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +// export default TimeEntryForm;
Quitar esto quizas?

2016-12-03 22:14 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +const mapStateToProps = (state) => { return {} }
Esto no es necesario.  Cuando no mapeas ninguna parte del estado al componente, pasas `null` como primer parámetro de `connect`.

En este case quedaría `export default connect(null, mapDispatchToProps)(TimeEntryForm);`

2016-12-03 22:14 UTC, diegomura commented on src/reducers/index.js
> +      project = {
Mirar comentario en el otro hilo

2016-12-04 15:49 UTC, martin-rifon commented
Bueno Diego, estuve craneando un poquito mas esto. Me quede con la solucion que acabo de pushear. Basicamente, saque ImmutableJS y los states nuevos los calculo usando operaciones inmutables de JS (como `concat`, que pusiste como ejemplo) y usando la operacion `Object.assign`. Tambien saque la parte de crear proyecto de la accion `CREATE_TIME_ENTRY`, porque me parecia tenia mucho sentido lo que dijiste de extraerlo en una (futura) accion `CREATE_PROJECT`.

Habiendo dicho esto, estuve tratando de hacer otra cosa y no pude hacer que saliera, me gustaria ver que opinas, para ver si encare mal la implementacion o no es algo que sea una buena practica en Redux:

- Crear una accion `FIND_OR_CREATE_PROJECT_BY_NAME`, se le pasa el nombre de un proyecto, si el proyecto existe, asigna al atributo `projectFound` del state el proyecto encontrado, sino, crea un proyecto nuevo con ese nombre y lo asigna al mismo atributo (`projectFound`).

- En el `mapDispatchToProps` de `TimeEntryForm.js`, primero despachar la accion `FIND_OR_CREATE_PROJECT_BY_NAME` (tomando el nombre del state de `TimeEntryForm`) y despues despachar la accion `CREATE_PROJECT` con el valor de `projectFound` del estado.

Segun lo que encontre, las acciones en Redux son sincronicas, por eso asumi que todo iba a estar bien. Pero siempre que leia el `projectFound` desde el `mapDispatchToProps` me retornaba el valor por defecto, asi que no segui con esa idea.

Muchas gracias de nuevo!

2016-12-04 16:55 UTC, diegomura requested changes

2016-12-04 16:55 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +      taskName: ReactDOM.findDOMNode(this.taskName).value
Usar `ref`

2016-12-04 16:55 UTC, diegomura commented on src/reducers/index.js
> +       });
la mejor forma de hacer esto es utilizando `spread operator` (https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Operadores/Spread_operator)

```
return {
  ...state,
  timeEntries: state.timeEntries.concat(project)
};
```

Creo que es mejor que no sea el handler el encargado de hacer `format`  de `moment.js`. El reducer debe ser lo mas agnostico posible. Si mañana queres crear un timeEntry utilizando algo que no sea un objeto de `moment`, no podrías. La action deberia ser dispatchada con la data misma, y no con objetos propietarios.

2016-12-04 17:03 UTC, diegomura commented
Respecto a lo que preguntabas, lo mejor sería no tener acciones que puedan tener varios desenlaces. Ademas, esa función no es pura, ya que el resultado (con un attr `projectFound` de mas o de menos) no depende exclusivamente del input.

Porque tener una action `CREATE_PROJECT` y otro `FIND_OR_CREATE_PROJECT_BY_NAME`?

Siempre que quieras filtrar un elemento de una colección, te recomiendo hacerlo con un `.filter` en el Componente, al menos que sea vital que pase por el State.

Lo mejor es no meter todo en este commit. Dejaria lo funcional que ya tenes y el tema de proyectos y eso verlo despues paso a paso. Yo veo este feature como algo que va a ser mas facil de agregar una vez tengas las timeEntries creadas en la API.

Saludos!

2016-12-04 18:26 UTC, martin-rifon commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +      taskName: ReactDOM.findDOMNode(this.taskName).value
En `taskName`? No estoy usando `ref` ya?

```
<FormControl
                  type="text"
                  placeholder="Task name"
                  ref={ (control) => { this.taskName = control; } }
                  className="task-name-input" />
```

2016-12-04 18:52 UTC, martin-rifon commented
>Porque tener una action CREATE_PROJECT y otro FIND_OR_CREATE_PROJECT_BY_NAME?
Tendria el create como una accion autocontenida para crear un proyecto y el find or create lo que haria seria llamar a una accion find y despues, si no hubo resultado, llamar a la accion create. Alguna que otra vez he usado el metodo find or create en algun framework tipo Rails.

>Siempre que quieras filtrar un elemento de una colección, te recomiendo hacerlo con un .filter en el Componente, al menos que sea vital que pase por el State.
Como harias algo como una busqueda con React? Un filter sobre la coleccion en el state? Que pasa si en el servidor hay elementos nuevos que no estan en la store? Haces un fetch que actualice el store y despues un filter sobre la coleccion en el store?

2016-12-05 03:07 UTC, diegomura requested changes

2016-12-05 03:07 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +      timeEntry.end = timeEntry.end.format(Configuration.dateFormat);
Los `.format` deberian hacerlos quien invocan la acción. `mapDispatchToProps` deberia retornar la acción en si misma, y no un wrapper.

Esto deberia quedar:
```js
const mapDispatchToProps = {
  createTimeEntry
};
```

y en `stopTimer: 
```js
const { start, projectId } = this.state;

this.props.createTimeEntry({
  start: start.format(),
  end: moment().format()
  projectId,     
  taskName: this.taskNameInput.value	
});
```

En esto hay que notar:

- La respuesta por defecto de `moment().format()` es valida para nosotros. No hay necesidad de pasar el formato
- Para los elementos de un form hay que usar `ref` (ver el link que te copie varios threads atras). Ahi es donde se crea `this.taskNameInput`

2016-12-05 03:07 UTC, diegomura commented on src/configuration.js
> +}
Esto es realmente necesario? Incrementa el acoplamiento del Componente y complejidad del proyecto

2016-12-05 03:25 UTC, diegomura commented
> Tendria el create como una accion autocontenida para crear un proyecto y el find or create lo que haria seria llamar a una accion find y despues, si no hubo resultado, llamar a la accion create.

Todavia no veo muy claro porqué querrias esta action, ni porque queres almacenar un proyecto separado en el state de redux. Cuando vas a seleccionar un proyecto, vi que usas un `select` para listar los proyectos existentes. Vos ya tenes todos los proyectos en tu estado, por lo que en ese caso solo tendrías que asignarle el project id a la task. 

Supongo tambien ahi tenes un input donde el usuario puede crear otro proyecto (esta es la parte donde mas me pierdo, pero es lo que intuyo por lo que comentas). En ese caso, lo que deberia dispararse una vez el usuario escribe el nombre del proyecto seria hacer un `CREATE_PROJECT` y listo. `FIND_OR_CREATE' seria para no tener proyectos con nombre duplicado? Si es por eso, no es reponsabilidad del reducer de manejarlo, sino del componente React mismo en chequar que no se puede crear uno con ese nombre.

Me gustaría que me explicaras mas en detalle para que y quien va a disparar esta action si es que lo que comente no se aplica a tu diseño.

>Como harias algo como una busqueda con React? Un filter sobre la coleccion en el state? Que pasa si en el servidor hay elementos nuevos que no estan en la store? Haces un fetch que actualice el store y despues un filter sobre la coleccion en el store?

Si yo quiero hacer una busqueda en una lista de algo que este en el redux state, una opción es inyectar la lista al componente React y hacer el filter ahi con la condicion de los elementos que quiero que tengan. De este modo, el state de redux siempre tiene toda la data, y cada componente decide que mostrar. Si vos modificas la lista en el estado en sí, deberias tener que traerte toda la info de nuevo (un fetch) cuando quieras mostrar todos los elementos.

Para que en el servidor hayan nuevos elementos, lo que se me ocurre ahora, tendria que pasar:

- Que sean modelos que de alguna forma se creen solos server-side
- Estar conectado desde varios clientes (o logueado dos veces en diferentes ventanas) y utilizar las dos.

No se me ocurre otra forma en la que el server deberia estar defasado de tu state si no son estas dos, ya que vos tenes el control del estado y de que se agrega y que se quita. En que situación pensas que te puede suceder esto?

2016-12-05 22:05 UTC, martin-rifon commented on src/configuration.js
> +}
Me gusto para hacer mas modificable el formato de la fecha. Podria dejarlo hardcodeado en el componente, pero si en algun otro componente quiero mostrar una fecha tendria que hardcodear el formato en ese tambien. De esta forma solamente se cambiaria el formato en el archivo `configuration.js`.

2016-12-05 22:16 UTC, martin-rifon commented
>Todavia no veo muy claro porqué querrias esta action, ni porque queres almacenar un proyecto separado en el state de redux. Cuando vas a seleccionar un proyecto, vi que usas un select para listar los proyectos existentes. Vos ya tenes todos los proyectos en tu estado, por lo que en ese caso solo tendrías que asignarle el project id a la task.

Supongo tambien ahi tenes un input donde el usuario puede crear otro proyecto (esta es la parte donde mas me pierdo, pero es lo que intuyo por lo que comentas). En ese caso, lo que deberia dispararse una vez el usuario escribe el nombre del proyecto seria hacer un CREATE_PROJECT y listo. `FIND_OR_CREATE' seria para no tener proyectos con nombre duplicado? Si es por eso, no es reponsabilidad del reducer de manejarlo, sino del componente React mismo en chequar que no se puede crear uno con ese nombre.

Me gustaría que me explicaras mas en detalle para que y quien va a disparar esta action si es que lo que comente no se aplica a tu diseño.

Va por donde dijiste si. Mi idea era que si el usuario escribia el nombre de un proyecto que ya existiese, la task se asociara a ese proyecto. Si el nombre no es un proyecto, se crea el proyecto nuevo y se asocia la task.

Esto se hace solo cuando el usuario aprieta el boton `stop`, porque se permite que se edite el nombre del proyecto mientras corre el tiempo. Por eso, la accion se ejecuta cuando el boton `stop` se aprieta. Una vez que se aprieta se hace toda la logica, ver si el proyecto existe, si no existe, se crea, despues se crea la task y listo.

>sino del componente React mismo en chequar que no se puede crear uno con ese nombre.
OK, entonces una posible solucion (tomando en cuenta la segunda parte de tu comentario) es que el componente React haga un filter sobre los `projects` del store y, si encuentra un `project` con el nombre igual a lo que hay en el input, asigne a `projectId` el id de ese `project`?

>No se me ocurre otra forma en la que el server deberia estar defasado de tu state si no son estas dos, ya que vos tenes el control del estado y de que se agrega y que se quita. En que situación pensas que te puede suceder esto?

Si, una posibilidad es esa, estar logueado de otro lado (app mobile por ejemplo). Tambien para el caso en el cual no haya filtro de proyecto por usuario. Aunque no son casos muy realistas para el ejercicio.

2016-12-05 23:34 UTC, diegomura commented
En primer lugar, creo que el comportamiento que vos describis se ajusta mas a una especie de `tag` y no tanto proyectos. En mi opinión, los proyectos no deberían crearse on the fly. Toggle lo implementa de esta forma, y yo creo que es la mejor:

<img width="377" alt="screen shot 2016-12-05 at 8 21 09 pm" src="https://cloud.githubusercontent.com/assets/5600341/20906800/c3df8eac-bb28-11e6-8036-282aefdebed0.png">

Esto no significa que tu approach no sea valido (al contrario!) pero como te dije antes, creo que va a ser mucho mas facil encarar este problema una vez estes creando time entries y tengas el sitio mas funcional. Creo va a ser mas cómodo seguir discutiendo de esto en un issue, pero que mientras tanto puedas continuar con las features mas sencillas.

Me quedo mas claro cual es el tipo de comportamiento que querés. Pueden existir varias soluciones posibles, ya que es un workflow un poco mas complejo. Si es así como deseas crearlo, yo lo que haría es que el Form reciba todos los proyectos (los podes listar, hacer autocompletado en el input, etc.) y si lo que ingresa no existe disparas la creación de uno. Luego, creas la entry con ese proyecto. Esto es en el aire. Cuando haya algo mas creado quizás sea mas facil verlo.

2016-12-05 23:41 UTC, martin-rifon commented
Mmm, me parece que lo voy a dejar como esta ahora, como sugeriste, no permitir que se creen proyectos on the fly. Ahora que lo pienso, lo que estaba describiendo parece mas un tag, tal como decis.

Si te parece que quedo saldada la PR, hago el merge y ya tengo esto como muy buena base para terminar lo que falta. Eso tambien lo dejo como PR y cuando este liquidado voy por la ultima etapa (pegar contra la API).

2016-12-06 04:33 UTC, diegomura approved these changes
Chequea los comentarios. Si te parece todo OK, mergealo y seguimos!

2016-12-06 04:33 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +                  // ref={ (control) => { this.taskName = control; } }
Los comentarios en JSX pueden dar problemas. Te sugiero que lo elimines

2016-12-06 04:33 UTC, diegomura commented on src/pages/Dashboard/Components/TimeEntryForm/TimeEntryForm.js
> +// const mapDispatchToProps = (dispatch, ownProps) => {
El comentario lo dejas por algo en especial? De no ser asi, mejor quitarlo 😄

2016-12-06 04:33 UTC, diegomura commented on src/configuration.js
> +}
Como te comente, no es necesario pasarle ningún formato a `moment().format()`. El default ya nos sirve para realizar este proyecto.

Por mas que lo que decís es correcto, a mi me gusta ver a los Componentes como unidades independientes, lo menos acoplados entre ellos posible. Tener el formato dentro del Componente que utiliza, por lo tanto, no lo considero como algo malo. Que sucede si mañana un componente debe entregar la fecha  con otro formato? Tendrías parte configurado desde los settings, y parte no. O lo que tampoco me gusta mucho: tener `dateFormatX`, `dateFormatY'.  Es una buena práctica hacer al Componente lo mas independiente posible. Que sea muy fácil extraerlo a una librería sin tener con la menor cantidad de configs posible.

De todos modos, es una opción valida y si te sentís mas cómodo así dale para adelante. Quizás te resulte interesante ver como esta definida API_URL en `webpack.config.js` y utilizar eso como configuración y variables globales.

2016-12-07 01:43 UTC, merged