External api
martin-rifon/workshop-react pull request #4
Opened 2016-12-12 00:07 UTC by martin-rifon

@diegomura 

Va la implementacion para que pegue contra la API. Ojo que también incluye los cambios de https://github.com/martin-rifon/workshop-react/pull/3 !

Muchas gracias!

2016-12-12 22:07 UTC, diegomura requested changes

2016-12-12 22:07 UTC, diegomura commented on src/app.js
> +                          applyMiddleware(thunk));
la forma correcta de indentar esto es:
```js
const store = createStore(
  foogl,
  loadState() || initialState,
  applyMiddleware(thunk)
);
```

2016-12-12 22:07 UTC, diegomura commented on src/layout/Layout.js
> +function mapStateToProps(state) {
Usar arrow functions (en este caso es lo mismo, pero mantiene un styleguide estandar)

```js
const mapStateToProps = (state) => ({
  loggedUser: state.loggedUser,
  loading: state.loading
})
```

2016-12-12 22:07 UTC, diegomura commented on src/pages/Login/Components/LoginForm/LoginForm.js
> +                onClick={doLogin}>
`onClick={::this.doLogin}`

2016-12-12 22:07 UTC, diegomura commented on src/pages/Login/Components/LoginForm/LoginForm.js
> +    const doLogin = this.doLogin.bind(this);
quitar variable y reemplazar por el comentario debajo

2016-12-12 22:07 UTC, diegomura commented on src/pages/Login/Components/LoginForm/LoginForm.js
> +function mapStateToProps(state) {
usar arrow functions

2016-12-12 22:07 UTC, diegomura commented on src/pages/Projects/Components/ProjectList/ProjectList.js
> +import { createProject } from '../../../../store/actions';
importar desde el root

2016-12-12 22:07 UTC, diegomura commented on src/reducers/index.js
> +  'ADD_PROJECT_TO_STORE': (state, action) => {
Creo que `TO_STORE` es redundante.

2016-12-13 00:36 UTC, martin-rifon commented
Diego, fueron los cambios.

2016-12-13 03:25 UTC, diegomura approved these changes

2016-12-13 03:25 UTC, diegomura commented
Gracias!

2016-12-13 11:02 UTC, merged